version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwe123
      POSTGRES_USER: admin
      POSTGRES_DB: ddos 
    ports:
        - "5432:5432"
  setup:
    image: ddos-setup
    depends_on:
        - "db"

  

